vim9script

source ~/.vim/plugin/logger.vim
logger#Trace('[vimrc]->Begin')

# Leader key   must be first
g:mapleader = "\<Space>"
g:maplocalleader = ','

if empty($MYVIMRC)
  $MYVIMRC = expand('<sfile>:p')
endif

# Enable extended % matching
packadd! matchit
# For filtering quickfix list
packadd! cfilter

# dict { 'topic': 'layer', 'lsp': 'coc'}
g:enable_layers = {
  'lsp': 'coc',
}
