vim9script
# Leader key   must be first
g:mapleader = "\<Space>"
g:maplocalleader = ','

if empty($MYVIMRC)
  var $MYVIMRC = expand('<sfile>:p')
endif

# Enable extended % matching
packadd! matchit
# For filtering quickfix list
packadd cfilter
